---

- name: Create kickstart file from template
  ansible.builtin.template:
    src: "{{ kickstart_template }}"
    dest: "{{ kickstart_file }}"
    mode: "0644"

- name: Test the kickstart file for consistency
  ansible.builtin.command:
    cmd: "{{ kickstart_venv_root }}/bin/ksvalidator -v {{ kickstart_template_version }} {{ kickstart_file }}"
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  changed_when: false
  when: kickstart_validator | bool
