---

- name: Define some variables for readability
  ansible.builtin.set_fact:
    image: /tmp/{{ kickstart_hostname }}.img
    mountpoint: /tmp/{{ kickstart_hostname }}
    fstype: vfat

- name: Delete the image if it is already present
  ansible.builtin.file:
    path: "{{ image }}"
    state: absent
  changed_when: false

- name: Create the file system with the loop device
  ansible.builtin.command:
    cmd: mkfs.vfat -C {{ image }} -n OEMDRV 1440
  changed_when: false

- name: Create mountpoint for floppy image
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: "0755"
  changed_when: false

- name: Mount the loop device  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: mount -o loop -t {{ fstype }} {{ image }} {{ mountpoint }}
  changed_when: false
  become: true
  tags: molecule-notest

- name: Create kickstart file from template
  ansible.builtin.template:
    src: "{{ kickstart_template }}"
    dest: "{{ mountpoint }}/ks.cfg"
    mode: "0644"
  changed_when: false

- name: Test the kickstart file for consistency
  ansible.builtin.command:
    cmd: "{{ kickstart_venv_root }}/bin/ksvalidator -v {{ kickstart_template_version }} {{ mountpoint }}/ks.cfg"
  changed_when: false
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  when: kickstart_validator | bool

- name: Unmount the image
  ansible.builtin.command:
    cmd: sudo umount {{ mountpoint }}
  changed_when: false
  tags: molecule-notest

- name: Delete mountpoints
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: absent
  changed_when: false
