---

- name: Define some variables for readability
  ansible.builtin.set_fact:
    image: /tmp/{{ kickstart_vm }}.img
    mountpoint: /tmp/{{ kickstart_vm }}
    fstype: vfat

- name: Delete the image if it is already present
  ansible.builtin.file:
    path: "{{ image }}"
    state: absent

- name: Create the file system with the loop device
  ansible.builtin.command:
    cmd: mkfs.vfat -C {{ image }} -n OEMDRV 1440

- name: Create mountpoint for floppy image
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: "0755"

- name: Mount the loop device  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: mount -o loop -t {{ fstype }} {{ image }} {{ mountpoint }}
  become: True
  tags: molecule-notest

- name: Create kickstart file from template
  ansible.builtin.template:
    src: "{{ kickstart_template }}"
    dest: "{{ mountpoint }}/ks.cfg"
    mode: "0644"
  changed_when: false

- name: Test the kickstart file for consistency
  ansible.builtin.command:
    cmd: ksvalidator -v {{ kickstart_template_version }} {{ mountpoint }}/ks.cfg
  changed_when: false
  when: kickstart_validator | bool

- name: Unmount the image
  ansible.builtin.command:
    cmd: sudo umount {{ mountpoint }}
  tags: molecule-notest

- name: Delete mountpoints
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: absent
