---

- name: Install OS packages
  ansible.builtin.package:
    name: "{{ kickstart_os_packages[ansible_os_family] }}"
    state: present
  become: yes

- name: Install pykickstart into a virtualenv
  ansible.builtin.include_tasks:
    file: venv.yml
  vars:
    venv_root: "{{ kickstart_venv_root }}"
    venv_packages: "{{ kickstart_pip_packages }}"

- name: Flip boolean so these steps can be skipped
  ansible.builtin.set_fact:
    kickstart_prepare: false
