---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    kickstart_distros:
      - { name: Rocky, version: 8, mode: iso }
      - { name: Rocky, version: 9, mode: iso }
      - { name: OracleLinux, version: 8, mode: iso }
      - { name: OracleLinux, version: 9, mode: iso }
      - { name: Rocky, version: 8, mode: fdd }
      - { name: Rocky, version: 9, mode: fdd }
      - { name: OracleLinux, version: 8, mode: fdd }
      - { name: OracleLinux, version: 9, mode: fdd }
  tasks:
    - name: Include role 'ansible-role-kickstart'
      ansible.builtin.include_role:
        name: ansible-role-kickstart
      vars:
        kickstart_distro: "{{ item.name }}"
        kickstart_version: "{{ item.version }}"
        kickstart_mode: "{{ item.mode }}"
      loop: "{{ kickstart_distros }}"
